name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Get version number
      run: |
        echo "APP_VERSION=1.0.$BUILD_ID-SNAPSHOT" >> $GITHUB_ENV
      env:
        BUILD_ID: ${{ github.run_id }}${{ github.run_attempt }}

    - name: Update version number
      run: mvn versions:set -DnewVersion=$APP_VERSION
      working-directory: ./SqlQueryBuilder

    - name: Build with Maven
      run: mvn -B package --file ./SqlQueryBuilder/pom.xml

    - name: Run unit tests
      run: mvn test

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Tests
        path: ./**/surefire-reports/*.xml
        reporter: java-junit

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        directory: ./SqlQueryBuilder